// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.Archive", b =>
                {
                    b.Property<int>("VersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_id");

                    b.Property<string>("ArchiveLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("archive_link");

                    b.Property<DateTime>("DownloadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("downloaded_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("ExpDate")
                        .HasColumnType("date")
                        .HasColumnName("exp_date");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UnarchivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("unarchived_at");

                    b.Property<string>("UnzippedFilesPath")
                        .HasColumnType("text");

                    b.HasKey("VersionId");

                    b.ToTable("delta_archive", (string)null);
                });

            modelBuilder.Entity("Data.Models.JobProgress", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("text")
                        .HasColumnName("job_id");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complete");

                    b.Property<int>("LastCheckpoint")
                        .HasColumnType("integer")
                        .HasColumnName("last_checkpoint");

                    b.HasKey("JobId");

                    b.ToTable("job_progress", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
