//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class HISTORIES {
    
    private HISTORIESITEM[] iTEMField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ITEM")]
    public HISTORIESITEM[] ITEM {
        get {
            return this.iTEMField;
        }
        set {
            this.iTEMField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HISTORIESITEM {
    
    private long cHANGEIDField;
    
    private long oBJECTIDField;
    
    private string aDROBJECTIDField;
    
    private string oPERTYPEIDField;
    
    private long nDOCIDField;
    
    private bool nDOCIDFieldSpecified;
    
    private System.DateTime cHANGEDATEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long CHANGEID {
        get {
            return this.cHANGEIDField;
        }
        set {
            this.cHANGEIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long OBJECTID {
        get {
            return this.oBJECTIDField;
        }
        set {
            this.oBJECTIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ADROBJECTID {
        get {
            return this.aDROBJECTIDField;
        }
        set {
            this.aDROBJECTIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string OPERTYPEID {
        get {
            return this.oPERTYPEIDField;
        }
        set {
            this.oPERTYPEIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long NDOCID {
        get {
            return this.nDOCIDField;
        }
        set {
            this.nDOCIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NDOCIDSpecified {
        get {
            return this.nDOCIDFieldSpecified;
        }
        set {
            this.nDOCIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime CHANGEDATE {
        get {
            return this.cHANGEDATEField;
        }
        set {
            this.cHANGEDATEField = value;
        }
    }
}
